baseURL = "/"
languageCode = "en-us"
title = "Ronan Gaillard"
theme = "cactus"


disableKinds = ["about"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "classic"
  mainSection = "posts"
  showProjectsList = false
  projectsUrl = "https://github.com/ronangaillard"

[[params.social]]
  name = "github"
  link = "https://github.com/ronangaillard"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/ronangaillard/"
